# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pool:
  vmImage: ubuntu-latest

steps:

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'cicd_notebooks'
    ArtifactName: 'cicd_databricks_notebooks_artifact'
    publishLocation: 'Container'
